#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Aug 15 21:26:02 2026

@author: dina.deifallah
"""

# Data is never committed (downloaded, or collected at runtime).
data/

# Trained model and metrics are regenerated by the pipeline.
artifacts/

# Python cruft.
__pycache__/
*.py[cod]
.venv/
venv/

# OS / editor noise.
.DS_Store
.spyproject/
.idea/
.vscode/